using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;

public class DialogFlow : MonoBehaviour
{
    // Start is called before the first frame update
    private bool isPressed;
    void Start()
    {
        isPressed = false;
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKey(KeyCode.P))
        {
            isPressed = true;
        }
        else
        {
            isPressed = false;
        }

        if (Input.GetKeyDown(KeyCode.P))
        {

            string cmd = @"python C:\Users\tomas\desktop\python\Main.py";
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"%windir%\system32\cmd.exe";
            start.Arguments = string.Format(cmd);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            Process.Start(start);
            /*using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                }
            }*/
        }
    }

    

    public bool IsPressed()
    {
        return isPressed;
    }
}
